repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
#-   repo: https://github.com/psf/black
#    rev: 22.10.0
#    hooks:
#    -   id: black
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.3.285
  hooks:
    - id: checkov
