name: Checkov
description: Executes Checkov Security Scan


runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
    #- uses: actions/checkout@v3

    - name: Checkov GitHub Action
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        framework: terraform
        # This will add both a CLI output to the console and create a results.sarif file
        output_format: cli
        #output_file_path: console,results.sarif

    #- name: Checkov GitHub Action
    #  id: checkov
    #  uses: bridgecrewio/checkov-action@v12
    #  with:
    #    # This will add both a CLI output to the console and create a results.sarif file
    #    output_format: cli,sarif
    #    output_file_path: console,results.sarif

    #- name: Upload SARIF file
    #  uses: github/codeql-action/upload-sarif@v2
    #  continue-on-error: true


    # Add resulting output to PR
    - name: Update Pull Request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      #env:
      #  CHECKOV: "${{ steps.checkov.outputs.results }}"
      with:
        github-token: ${{ github.token }}
        script: |
          const output = `#### Checkov Test ${{ steps.checkov.outcome }}

          <details><summary>Checkov Results</summary>

          ${{ steps.checkov.outputs.results }}

          </details>

          *Pushed by: @${{ github.actor }}, Action: ${{ github.event_name }}`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
