name: "Auto Deploy"
run-name: Auto Deploy triggered by @${{ github.actor }}
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  release:
    permissions: write-all
    name: "release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tag of main branch
        uses: ./.github/actions/release
        with:
          MESSAGE: 'PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

  deploy:
    name: deploy
    needs: ["release"]
    uses: ./.github/workflows/deploy.yml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}
    concurrency: ${{ matrix.environment }}
    with:
      ENVIRONMENT_NAME: ${{ matrix.environment }}
      ROLE_DURATION_SECONDS: 3600

    secrets: inherit
