name: "Auto Deploy"
run-name: Auto Deploy triggered by @${{ github.actor }}
on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: release
    permissions:
      id-token: write
      contents: write
      #issues: write
      pull-requests: write
      #deployments: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: Tag of main branch
      #  uses: ./.github/actions/release
      #  with:
      #    MESSAGE: 'PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

  deploy:
    name: deploy
    permissions:
      id-token: write
      contents: read
    needs: ["release"]
    uses: ./.github/workflows/deploy.yml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}
    concurrency: ${{ matrix.environment }}
    with:
      ENVIRONMENT_NAME: ${{ matrix.environment }}
      ROLE_DURATION_SECONDS: 3600
    secrets: inherit
