name: "Auto Deploy"
run-name: Auto Deploy triggered by @${{ github.actor }}
on:
  push:
    branches:
      - "main"

jobs:


  deploy:
    name: deploy
    permissions:
      id-token: write
      contents: read
    #needs: ["release"]
    uses: ./.github/workflows/deploy.yml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}
    concurrency: ${{ matrix.environment }}
    with:
      ENVIRONMENT_NAME: ${{ matrix.environment }}
      ROLE_DURATION_SECONDS: 3600
    secrets: inherit
