name: "Multi Env Deploy"
run-name: Multi Env Deploy by @${{ github.actor }}
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest

    steps:
      - name: Tag of main branch
        uses: ./.github/actions/release
        with:
          MESSAGE: "test"

  deploy:
    name: deploy
    needs: ["release"]
    uses: ./.github/workflows/deploy.yml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}
    concurrency: ${{ matrix.environment }}
    with:
      ENVIRONMENT_NAME: ${{ matrix.environment }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VERSION: ${{ vars.TF_VERSION }}
      ROLE_DURATION_SECONDS: 3600
      
    secrets:
      IDENTITY_ROLE: ${{ secrets.IDENTITY_ROLE }}
