name: "Auto Plan"
run-name: Auto Plan triggered by @${{ github.actor }} - ${{ github.event_name }}
on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  security-events: write
  deployments: write
jobs:
  # This workflow contains a single job called "scan"



  plan:
    name: plan
    #needs: ["scan"]
    uses: ./.github/workflows/plan.yml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}
    concurrency: ${{ matrix.environment }}
    with:
      ENVIRONMENT_NAME: ${{ matrix.environment }}
      ROLE_DURATION_SECONDS: 3600
    secrets: inherit
